# -*- coding: utf-8 -*-
"""分享書籍、後台密碼重設、書籍編輯與訂單詳情的譯文。"""

T = {
    # ---------- 分享書籍 ----------
    '分享書籍': ('Share this book', 'この本を共有', '이 책 공유', '分享书籍'),
    '分享到其他 App': ('Share to another app', '他のアプリで共有', '다른 앱으로 공유', '分享到其他 App'),

    # ---------- 訂單流程節點 ----------
    '成立訂單': ('Order placed', '注文成立', '주문 생성', '成立订单'),
    '付款': ('Paid', '支払い', '결제', '付款'),
    '賣家放書': ('Seller dropped off', '出品者が預け入れ', '판매자 보관', '卖家放书'),
    '買家取書': ('Buyer collected', '購入者が受け取り', '구매자 수령', '买家取书'),
    '完成': ('Completed', '完了', '완료', '完成'),

    # ---------- 後台：編輯書籍 ----------
    '編輯書籍資料': ('Edit book details', '書籍情報を編集', '도서 정보 편집', '编辑书籍资料'),
    r'賣家 ${book.sellerName}・儲存後會通知他': (r'Seller $p0 — they are notified on save', r'出品者 $p0・保存時に通知されます', r'판매자 $p0 · 저장하면 알림이 갑니다', r'卖家 $p0・保存后会通知他'),
    '售價（代幣）': ('Price (coins)', '価格（コイン）', '가격 (코인)', '售价（代币）'),
    '10 或 13 位數字': ('10 or 13 digits', '10桁または13桁', '10자리 또는 13자리', '10 或 13 位数字'),
    '分類': ('Category', 'カテゴリー', '카테고리', '分类'),
    '商品描述': ('Description', '商品説明', '상품 설명', '商品描述'),
    '書名必填': ('A title is required', 'タイトルは必須です', '제목은 필수입니다', '书名必填'),
    '沒有變更': ('Nothing changed', '変更はありません', '변경 사항이 없습니다', '没有变更'),

    # ---------- 後台：重設密碼 ----------
    '重設密碼': ('Reset password', 'パスワードをリセット', '비밀번호 재설정', '重置密码'),
    '產生臨時密碼': ('Generate a temporary password', '仮パスワードを発行', '임시 비밀번호 발급', '生成临时密码'),
    '臨時密碼': ('Temporary password', '仮パスワード', '임시 비밀번호', '临时密码'),
    r'$nickname 的密碼已重設。這組密碼只會出現這一次，關掉後無法再查看。': (r"$p0's password has been reset. This password is shown once only — it cannot be viewed again after closing.", r'$p0のパスワードをリセットしました。このパスワードは一度きりの表示で、閉じると二度と確認できません。', r'$p0 님의 비밀번호를 재설정했습니다. 이 비밀번호는 한 번만 표시되며 닫으면 다시 볼 수 없습니다.', r'$p0 的密码已重置。这组密码只会出现这一次，关闭后无法再查看。'),
    '請提醒對方登入後立刻到「設定 → 更改密碼」改掉。': ('Remind them to change it at Settings → Change password right after signing in.', 'ログイン後すぐに「設定 → パスワード変更」で変更するよう伝えてください。', '로그인 후 바로 설정 → 비밀번호 변경에서 바꾸도록 안내하세요.', '请提醒对方登录后立刻到“设置 → 更改密码”改掉。'),
    '已複製臨時密碼': ('Temporary password copied', '仮パスワードをコピーしました', '임시 비밀번호를 복사했습니다', '已复制临时密码'),
    '複製': ('Copy', 'コピー', '복사', '复制'),
    '不能重設其他管理員的密碼': ("You cannot reset another admin's password", '他の管理者のパスワードはリセットできません', '다른 관리자의 비밀번호는 재설정할 수 없습니다', '不能重置其他管理员的密码'),
    '產生一組臨時密碼交給使用者': ('Generate a temporary password to hand over', '仮パスワードを発行して本人に渡します', '임시 비밀번호를 발급해 전달합니다', '生成一组临时密码交给用户'),

    # ---------- 後台：訂單詳情 ----------
    '已複製訂單編號': ('Order number copied', '注文番号をコピーしました', '주문 번호를 복사했습니다', '已复制订单编号'),
    '找不到這筆訂單': ('Order not found', 'この注文が見つかりません', '주문을 찾을 수 없습니다', '找不到这笔订单'),
    '代幣支付': ('Paid with coins', 'コイン払い', '코인 결제', '代币支付'),
    '銀行轉帳': ('Bank transfer', '銀行振込', '계좌 이체', '银行转账'),
    '尚未付款': ('Not paid yet', '未払い', '미결제', '尚未付款'),
    '流程': ('Progress', '進行状況', '진행 상황', '流程'),
    '尚未發生': ('Not yet', '未到達', '아직 아님', '尚未发生'),
    '買賣雙方': ('Buyer and seller', '取引相手', '거래 당사자', '买卖双方'),
    '品項': ('Items', '商品', '항목', '品项'),
    '（書籍已刪除）': ('(book deleted)', '（書籍は削除済み）', '(삭제된 도서)', '（书籍已删除）'),
    '尚未指派': ('Not assigned yet', '未割り当て', '미배정', '尚未指派'),
    '已複製取書碼': ('Pickup code copied', '受け取りコードをコピーしました', '수령 코드를 복사했습니다', '已复制取书码'),
    '錢包異動': ('Wallet activity', 'ウォレットの動き', '지갑 변동', '钱包变动'),
    '退款紀錄': ('Refunds', '返金記録', '환불 기록', '退款记录'),
    r'申請於 ${formatDateTime(refund.createdAt)}，尚未處理': (r'Requested $p0, not processed yet', r'$p0に申請、未処理', r'$p0 신청, 미처리', r'申请于 $p0，尚未处理'),
    r'處理於 ${formatDateTime(refund.processedAt)}': (r'Processed $p0', r'$p0に処理', r'$p0 처리', r'处理于 $p0'),
    '申訴': ('Disputes', '申し立て', '이의 제기', '申诉'),
    r'申請於 ${formatDateTime(dispute.createdAt)}': (r'Filed $p0', r'$p0に申請', r'$p0 신청', r'申请于 $p0'),
    r'裁決於 ${formatDateTime(dispute.resolvedAt)}': (r'Decided $p0', r'$p0に裁定', r'$p0 판정', r'裁决于 $p0'),
    r'建立於 ${formatDateTime(detail.order.createdAt)}': (r'Created $p0', r'$p0に作成', r'$p0 생성', r'创建于 $p0'),
    '編輯': ('Edit', '編集', '편집', '编辑'),
    '已更新': ('Updated', '更新しました', '수정했습니다', '已更新'),
}

T[r'${detail.nickname} 目前的密碼會立刻失效，必須改用接下來產生的臨時密碼登入。\n\n密碼由系統產生，你不能自己指定。'] = (
    r"$p0's current password stops working immediately; they must sign in with the temporary password generated next.\n\nThe password is generated by the system — you cannot choose it.",
    r'$p0の現在のパスワードは直ちに使えなくなり、次に発行される仮パスワードでログインすることになります。\n\nパスワードはシステムが生成します。指定はできません。',
    r'$p0 님의 현재 비밀번호는 즉시 사용할 수 없게 되며, 다음에 발급되는 임시 비밀번호로 로그인해야 합니다.\n\n비밀번호는 시스템이 생성하며 직접 지정할 수 없습니다.',
    r'$p0 当前的密码会立刻失效，必须改用接下来生成的临时密码登录。\n\n密码由系统生成，你不能自己指定。',
)

T['已核准'] = ('Approved', '承認済み', '승인됨', '已核准')

T['待退款'] = ('Awaiting refund', '返金待ち', '환불 대기', '待退款')
T['不予退款'] = ('Declined', '返金不可', '환불 거절', '不予退款')
