@startuml
skinparam monochrome true
skinparam shadowing false
skinparam dpi 220
skinparam defaultFontName "PingFang TC"
skinparam defaultFontSize 13
hide empty description

[*] --> 待受理 : 買家或賣家申請爭議
待受理 --> 已裁決 : 管理員裁決

state 已裁決 {
  [*] --> 人工退款 : 判定人工退款
  [*] --> 自動退款 : 判定自動退款
  [*] --> 駁回爭議 : 判定駁回爭議
  [*] --> 協調結案 : 判定協調結案
}
已裁決 --> [*]
@enduml
