// AI 客服知識庫的說明文字由這裡的數字組成，服務若另寫一份數字，客服回答就會和實際規則不一致。
const list = (values) => Object.freeze([...values]);

module.exports = Object.freeze({
  ORDER_CANCELLABLE_STATUSES: list(['pending_payment', 'pending_deposit']),
  ORDER_DEPOSIT_DAYS: 7,
  ORDER_PICKUP_DAYS: 7,
  ORDER_AUTO_COMPLETE_HOURS: 24,
  DISPUTE_WINDOW_HOURS: 24,

  DEPOSIT_PAUSE_DAYS: 7,
  DEPOSIT_REMIND_DAYS: 3,
  DEPOSIT_ESCALATE_DAYS: 14,

  RESERVATION_HOLD_HOURS: list([24, 48, 72]),
  RESERVATION_RESPONSE_HOURS: 24,
  RESERVATION_MAX_ACTIVE: 5,

  LISTING_MAX_PRICE: 99999,
  LISTING_MAX_IMAGES: 10,
  LISTING_REVIEW_PRICE: 3000,

  CHAT_TRANSFER_MAX_AMOUNT: 100000,
  CHAT_REQUEST_TTL_HOURS: 72,

  ACCOUNT_DELETION_GRACE_DAYS: 30,
  LEVEL_POINTS_PER_ORDER: 10,

  CABINET_GEOFENCE_M: 200,
  CABINET_DOOR_OPEN_SECONDS: 30,
  CABINET_DOOR_EXTRA_SECONDS: 15,
  CABINET_DOOR_OPEN_MAX_SECONDS: 90,
  CABINET_DOOR_MAX_BOOKS: 3,
  CABINET_ORDER_RESERVED_DOORS: 1,
  CABINET_PREDEPOSIT_MAX_PER_SELLER: 1,
  CABINET_QR_REFRESH_SECONDS: 30,
  CABINET_QR_TTL_SECONDS: 45,
  CABINET_SELECT_SECONDS: 60,
  CABINET_MATCH_SECONDS: 60,
  CABINET_MATCH_CHOICES: 9,
  CABINET_COOLDOWN_STRIKES: 2,
  CABINET_COOLDOWN_MINUTES: 10
});
