name: Generate 3D Contribs for Team

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        username: [GaryChen33, Shelly9457, XuKaiJun914, xuan26] 
    steps:
      - uses: actions/checkout@v4
      
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ matrix.username }}
      
      - name: Rename and Move
        run: |
          mkdir -p team-contribs
          mv profile-3d-contrib/profile-night-rainbow.svg team-contribs/${{ matrix.username }}-3d.svg

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add team-contribs/
          git commit -m "Update 3D graph for ${{ matrix.username }}" || echo "No changes to commit"
          git pull --rebase
          git push
